# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24de8d562ec90adfd85eb42ba470f917f05ce26be5d36c0b5eabe3b7f03f8a48e7ab7343a1add880b49c43cb2623cfcd7a0c5af0449a863199e8fe57a2a69dcb

test:
  secret_key_base: ee05bfd910906bafabd35e86fe618b081add1cdaca3f4027f6c7dd3a7f35ecdd98fd229e5e1acbabcd28df8b8311733018ee2cd29adcce2bfd7e7fc407badb5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
